name: Brakeman Code Scan

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  brakeman-scan:
    name: Brakeman Code Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Generate Sarif Output
      continue-on-error: true
      run: bundle exec brakeman -f sarif -o brakeman.sarif

    - name: Upload Sarif Output
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: brakeman.sarif
