name: Lint

on:
  workflow_call:

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Setup Branch
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop --display-cop-names

  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Setup Branch
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Run Brakeman
        run: bundle exec brakeman
